[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm config set registry https://registry.npmmirror.com",
  "npm ci --omit=dev --no-audit --no-fund"
]

[phases.build]
cmds = ["npm run build:server"]

[start]
cmd = "npm start"
